# Generated by Django 2.1.3 on 2020-01-23 19:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.ImageField(upload_to=accounts.models.profile_path),
        ),
    ]
