# Generated by Django 2.1.3 on 2020-01-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200123_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image_url',
            new_name='profile_image',
        ),
    ]
